name: ChunkAnalyzer
main: io.github.meeples10.chunkanalyzer.Main
version: %PROJECT_VERSION%
author: Meeples10
description: %PROJECT_DESCRIPTION%
api-version: 1.16
commands:
  chunkanalyzer:
    description: Start teleporting the player out from [0, 0] in a spiral
    usage: /chunkanalyzer
    aliases: [ca]
    default: true
